// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFSQLiteDemo.Migrations
{
    [DbContext(typeof(KiteDBContext))]
    partial class KiteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Kite", b =>
                {
                    b.Property<int>("KiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("KiteColor")
                        .HasColumnType("TEXT");

                    b.Property<string>("KiteDesigner")
                        .HasColumnType("TEXT");

                    b.HasKey("KiteId");

                    b.ToTable("Kites");
                });
#pragma warning restore 612, 618
        }
    }
}
