// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFSQLiteDemo.Migrations
{
    [DbContext(typeof(KiteDBContext))]
    [Migration("20211004074659_AddedNewKite2")]
    partial class AddedNewKite2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("Kite", b =>
                {
                    b.Property<int>("KiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("KiteColor")
                        .HasColumnType("INTEGER");

                    b.Property<string>("KiteDesigner")
                        .HasColumnType("TEXT");

                    b.HasKey("KiteId");

                    b.ToTable("Kites");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Kite");
                });

            modelBuilder.Entity("EFSQLiteDemo.Model.KiteUpdateOctober4th", b =>
                {
                    b.HasBaseType("Kite");

                    b.Property<int>("KiteHeight")
                        .HasColumnType("INTEGER");

                    b.Property<double>("KiteWeight")
                        .HasColumnType("REAL");

                    b.Property<int>("KiteWidth")
                        .HasColumnType("INTEGER");

                    b.HasDiscriminator().HasValue("KiteUpdateOctober4th");
                });
#pragma warning restore 612, 618
        }
    }
}
