// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFMSSQLServerDemo.Migrations
{
    [DbContext(typeof(KiteDBContext))]
    partial class KiteDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kite", b =>
                {
                    b.Property<int>("KiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("KiteColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KiteDesigner")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KiteId");

                    b.ToTable("Kites");
                });
#pragma warning restore 612, 618
        }
    }
}
