using projectcrudresume.DatabaseClasses;
using projectcrudresume.Models;
using projectcrudresume.PostmanClasses;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Principal;
using System.Web;

namespace projectcrudresume.Helpers
{
    public class UserHelpers
    {

        private ApplicationDbContext db = new ApplicationDbContext();
        //when a new account is registered, we need to make them automatically added to 
        //UserProfile table.
        //also User Resume
        //TODO15 see if we should retire the suer profile table. 
        public bool AddUserProfileToDatabase(string email,string AspNetUsersUniqueIdentifier)
        {
            bool response = false;

            //add the email and other details to the database
            //UserProfile
            var tempUserProfile = new UserProfile();
            tempUserProfile.UserActiveStatus = true;
            tempUserProfile.UserEmail = email;
            tempUserProfile.UserUniqueKey = email;
            //lets update our unique identifier that is auto generated by the asp identity system
            tempUserProfile.AspNetUsersUniqueIdentifier = AspNetUsersUniqueIdentifier;

            var tempUserResume = new UserResume();
            tempUserResume.UserEmail = email;
            tempUserResume.Email = email;
            tempUserResume.AspNetUsersUniqueIdentifier = AspNetUsersUniqueIdentifier;

            try
            {
                //lets add this to your database 
                db.UserProfiles.Add(tempUserProfile);
                db.UserResumes.Add(tempUserResume);
                db.SaveChanges();
                response = true;
            }
            catch
            {

            }

            return response;
        }

        public UserProfile GetUserProfile(string AspNetUsersUniqueIdentifier)
        {
            var response = db.UserProfiles.Select(x => x).Where(x => x.AspNetUsersUniqueIdentifier == AspNetUsersUniqueIdentifier).FirstOrDefault();

            var tempUserProfile = new UserProfile();
            if(response == null)
            {
                tempUserProfile.UserEmail = "Email Not Found";
                tempUserProfile.UserActiveStatus = false;
                tempUserProfile.UserUniqueKey = "Email Not Found";
                tempUserProfile.AspNetUsersUniqueIdentifier = "No Id to provide";
            }
            else
            {
                tempUserProfile = response;
            }
            return tempUserProfile;
        }

        internal UserProfileViewModel GetUserProfileViewModel(string userId)
        {
            var tempUserProfileViewModel = new UserProfileViewModel();
            var tempUserHelpers = new UserHelpers();

            UserProfile tempUserProfile = tempUserHelpers.GetUserProfile(userId);
            tempUserProfileViewModel.UserActiveStatus = tempUserProfile.UserActiveStatus;
            tempUserProfileViewModel.UserEmail = tempUserProfile.UserEmail;
            tempUserProfileViewModel.UserUniqueKey = tempUserProfile.UserUniqueKey;

            return tempUserProfileViewModel;
        }
    }
}